# Generated by Django 3.0.3 on 2020-02-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('year', models.CharField(db_index=True, max_length=10)),
                ('awards', models.CharField(max_length=10)),
                ('nominations', models.CharField(max_length=10)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('title', 'year')},
            },
        ),
    ]
